env:
  es6: true
  node: true
extends:
  - '@nuxtjs/eslint-config-typescript'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
root: true
rules:
  no-tabs:
    - error
    - allowIndentationTabs: true
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - always